### ISSUE TITLE
Could the cover image be used as a hyperlink?

### ISSUE THREAD

**Issue by FabSchwul** [Groctel/aqademia#2]
I wanna use the cover image in a way that you could click it so it delivers you to the organization's main page, the github project, etc.

I don't know if this can be done, or if it needs any change at template implementation level. Thanks for all!

**Comment by Groctel** [comment]
I've been working on this for a couple of days and don't find a way to make it work seamlessly for all LaTeX engines, since `hyperref` requires different formats for different compilers (for example `XeLaTeX` only accepts `.pdf` files when linking a non-textual element). Add to it that this is a template for *printable* documents, so I don't see how general users would benefit from a pure computer UI element. As of now, Aqademia offers an `\hypersetup` for convenience and style, but it's not at all a primary feature.
